/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.ice.plugin.hello

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * https://juejin.cn/post/6887581345384497165
 * 建立文件夹后使用gradle init创建单独工程，可以直接将工程文件夹拷贝到项目中
 * 删除gradle、settings.gradle、.gradle、.idea等文件可作为module
 */
public class HelloPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'com.ice.plugin.hello.greeting'")
            }
        }
    }
}
